ALTER TABLE `agent_stats`.`stats` 
ADD COLUMN `prime_challenge` BIGINT(20) UNSIGNED NULL DEFAULT NULL AFTER `recursions`,
ADD COLUMN `stealth_ops` BIGINT(20) UNSIGNED NULL DEFAULT NULL AFTER `prime_challenge`,
ADD COLUMN `opr_live` BIGINT(20) UNSIGNED NULL DEFAULT NULL AFTER `stealth_ops`,
ADD COLUMN `ocf` BIGINT(20) UNSIGNED NULL DEFAULT NULL AFTER `opr_live`,
ADD COLUMN `intel_ops` BIGINT(20) UNSIGNED NULL DEFAULT NULL AFTER `ocf`,
ADD COLUMN `ifs` BIGINT(20) UNSIGNED NULL AFTER `intel_ops`;